# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-04 01:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0003_goodcategoryvisit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodcategoryvisit',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='访问日期'),
        ),
    ]
